### ISSUE TITLE
numbers disappear when digits change

### ISSUE THREAD

**Issue by gaoryrt** [alikinvv/stepper#3]
![May-11-2019 15-16-04](https://user-images.githubusercontent.com/5306513/57566533-1b65f700-7400-11e9-99f1-19fad0c51d90.gif)

and 99 should be center aligned

**Comment by alikinvv** [comment]
Fixed on https://github.com/alikinvv/stepper/commit/88eff2fdf5f9f42782c4f621c919c37dbced2dd7 https://github.com/alikinvv/stepper/commit/3612b3e9694afba51cdb5232abe95fb3ddebb9a6
